apiVersion: v1
kind: Service
metadata:
  name: back-end-worker
  labels:
    app: back-end-env-sec
spec:
  type: ClusterIP
  ports:
  - name: http-back-end-worker
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: back-end-worker
