apiVersion: batch/v1
kind: Job
metadata:
  name: jobdbmigratelhpracticeapi
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 10
  activeDeadlineSeconds: 300
  template:
    spec:
      containers:
      - name: lhpracticeapi
        image: default
        command: ["npx", "sequelize-cli", "db:migrate", "--env", "development"]

      restartPolicy: Never
  backoffLimit: 1