apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployeformsapi
  labels:
    app: deployeformsapi
spec:
  revisionHistoryLimit: 3
  #replicas: 2
  selector:
    matchLabels:
      app: deploylheformsapi
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: deployeformsapi
    spec:
      serviceAccountName: sqs-s3-stage
      containers:
      - name: lheformsapi
        image: image_url/eforms-api-stage
        envFrom:
          - configMapRef:
              name: eforms-env-cm
          - secretRef:
              name: eforms-env-sec
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 512m
          requests:
            cpu: 300m