apiVersion: v1
kind: Service
metadata:
  name: serviceeformsapi
spec:
  selector:
    app: deployeformsapi
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32035
