apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app: prometheus
resources:
- ../../../base/apps/monitoring/prometheus
- prometheus-ingress.yaml
patchesStrategicMerge:
- deployment.yaml