apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-communication-api
commonLabels:
  app: deploypatientfrontend
resources:
  - communication-cm.yaml
  - communication-sec.yaml
  - ../../../base/apps/api/communication-api
  - hpa.yaml
  - ingress-api.yaml
patchesStrategicMerge:
  - deployment.yaml
patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: deploylhcommunicationapi
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: deploylhcommunicationapi
- target:
    version: v1
    kind: Ingress
    name: ingresslhcommunicationapi
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: staging-api.linear.health
    - op: replace
      path: /spec/rules/0/http/paths/0/backend/service/name
      value: servicelhcommunicationapi
images:
- name: 052758603943.dkr.ecr.us-east-2.amazonaws.com/lh-communication-api-stage
  newTag: '2'
