apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeexporter-stage
  namespace: argocd
spec:
  project: test-stage
  source:
    repoURL: 'git@github.com:test/Gitops.git'
    path: deployments/monitoring/node-exporter
    targetRevision: deploy-stage
    directory:
      recurse: false
      jsonnet: {}
  destination:
    namespace: monitoring
    name: test-eks-stage
  syncPolicy:   
    syncOptions:
      - CreateNamespace=true