apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-frontend-stage
  namespace: argocd
spec:
  project: test-stage
  source:
    repoURL: 'git@github.com:linear-health/Gitops.git'
    path: deployments/frontend/admin-frontend
    targetRevision: deploy-stage
    directory:
      recurse: false
      jsonnet: {}
  destination:
    namespace: stage-admin-frontend
    name: test-eks-stage
  syncPolicy:   
    syncOptions:
      - CreateNamespace=true