apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - name: http-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis