apiVersion: v1
kind: Service
metadata:
  name: servicepatientfrontend
  namespace: default
  labels:
    app: laravel
spec:
  selector:
    app: deploypatientfrontend
  type: NodePort
  ports:
  - name: http-patient
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30500