apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: image_url        
          envFrom:
            - configMapRef:
                name: laravel-env-cm
            - secretRef:
                name: laravel-env-sec
          ports:
            - containerPort: 80
              name: http-laravel              
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   failureThreshold: 10            
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1020m"
              memory: "4096Mi"
          #securityContext:
          #  runAsUser: 82
          #  runAsGroup: 82