apiVersion: v1
kind: Service
metadata:
  name: serviceadminfrontend
spec:
  selector:
    app: deployadminfrontend
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30550