apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app: grafana
resources:
- ../../../base/apps/monitoring/grafana
- grafana-ingress.yaml
patchesStrategicMerge:
- deployment.yaml