apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - prometheus-cluster-role.yaml
    - prometheus-config.yaml
    - deployment.yaml
    - prometheus-service.yaml
commonLabels:
  app: prometheus